// Generated by scripts/build_questions.py from the Markdown question bank.
const QUESTIONS = [
  {
    "prompt": "What does ורמינהו tell us here?",
    "options": [
      "Now we will tell a story.",
      "Here is another teaching that seems to disagree.",
      "Everyone agrees with this answer.",
      "We have finished the discussion."
    ],
    "correct": 1,
    "feedback": "ורמינהו introduces a clash between teachings. Here, sunrise seems to clash with the Mishnah's later deadline."
  },
  {
    "prompt": "What does הנץ החמה mean?",
    "options": [
      "Sunset",
      "Midday",
      "Midnight",
      "Sunrise"
    ],
    "correct": 3,
    "feedback": "הנץ החמה means sunrise."
  },
  {
    "prompt": "What does כדי mean here?",
    "options": [
      "In order to",
      "Even though",
      "Instead of",
      "Afterward"
    ],
    "correct": 0,
    "feedback": "כדי introduces a purpose: in order to do something. It does not introduce an objection here."
  },
  {
    "prompt": "What does שיסמוך mean here?",
    "options": [
      "That he should repeat",
      "That he should leave out",
      "That he should place next to",
      "That he should ask about"
    ],
    "correct": 2,
    "feedback": "שיסמוך means placing things next to each other. Here, the blessing of redemption comes directly before the Amidah."
  },
  {
    "prompt": "What does ביום mean?",
    "options": [
      "At night",
      "During the day",
      "Before sunrise",
      "On the next day"
    ],
    "correct": 1,
    "feedback": "ביום means during the day. The ב־ here means “in” or “during.”"
  },
  {
    "prompt": "What does כי תניא ההיא mean here?",
    "options": [
      "Who disagreed with that teaching?",
      "That teaching was never taught.",
      "When that teaching was taught…",
      "Why was that teaching forgotten?"
    ],
    "correct": 2,
    "feedback": "כי תניא ההיא means “When that teaching was taught…” The next word explains whom it concerns."
  },
  {
    "prompt": "What is כי תניא ההיא — לותיקין doing in this discussion?",
    "options": [
      "Answering by explaining whom the earlier teaching is about",
      "Asking for the meaning of an unfamiliar word",
      "Bringing a new objection from the Mishnah",
      "Starting a story about a different subject"
    ],
    "correct": 0,
    "feedback": "The answer explains that the sunrise teaching concerns the practice of the ותיקין."
  },
  {
    "prompt": "Who are the ותיקין in this passage?",
    "options": [
      "People who have never learned Mishnah",
      "People who missed the morning prayer",
      "People who are travelling at night",
      "People especially careful in performing mitzvot"
    ],
    "correct": 3,
    "feedback": "Here, ותיקין describes people especially careful in performing mitzvot, including the timing of prayer."
  },
  {
    "prompt": "What does דאמר mean here, before רבי יוחנן?",
    "options": [
      "But he asked",
      "For he said",
      "If he forgot",
      "Until he returned"
    ],
    "correct": 1,
    "feedback": "דאמר means “for he said” here. It introduces Rabbi Yochanan's supporting statement."
  },
  {
    "prompt": "Why does the Gemara bring Rabbi Yochanan's statement here?",
    "options": [
      "To introduce an unrelated rule about evening prayer",
      "To show that the Mishnah has no time limit",
      "To support the explanation about the ותיקין",
      "To ask who wrote the Mishnah"
    ],
    "correct": 2,
    "feedback": "Rabbi Yochanan describes the ותיקין finishing Shema at sunrise, supporting the answer just given."
  },
  {
    "prompt": "What does היו גומרים mean?",
    "options": [
      "They used to finish",
      "They were about to ask",
      "They refused to begin",
      "They forgot to say"
    ],
    "correct": 0,
    "feedback": "היו גומרים means “they used to finish.” Here it refers to finishing Shema."
  }
];
