"""Regenerate browser content from the reviewed Markdown question bank."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / 'content/berachot-26a-opening-quiz.md').read_text(encoding='utf-8')
answers = {int(n): (ord(letter) - ord('A'), feedback.strip()) for n, letter, feedback in re.findall(r'^\| (\d+) \| ([A-D]) \| (.*?) \|$', source, re.M)}
questions = []
for number, prompt, body in re.findall(r'### (\d+)\. (.*?)\n(.*?)(?=\n### |\n## |\Z)', source, re.S):
    options = re.findall(r'^[A-D]\. (.*)$', body, re.M)
    correct, feedback = answers[int(number)]
    assert len(options) == 4, f'Question {number} needs four options'
    questions.append(dict(prompt=prompt, options=options, correct=correct, feedback=feedback))
assert len(questions) == 11
(root / 'questions.js').write_text('// Generated by scripts/build_questions.py from the Markdown question bank.\nconst QUESTIONS = ' + json.dumps(questions, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Generated {len(questions)} questions.')
